version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: webrise
      POSTGRES_USER: webrise
      POSTGRES_PASSWORD: webrise
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/webrise
      SPRING_DATASOURCE_USERNAME: webrise
      SPRING_DATASOURCE_PASSWORD: webrise
    ports:
      - "8080:8080"

volumes:
  dbdata:
