spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://postgres:5432/webrise
    username: webrise
    password: webrise
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
logging:
  level:
    root: info
    com.silveo.webrise: debug
